export interface BilingualOption {
  value: string;
  zh: string;
  en: string;
}

export const COUNTRIES: BilingualOption[] = [
  { value: 'China', zh: '中国', en: 'China' },
  { value: 'Japan', zh: '日本', en: 'Japan' },
  { value: 'United States', zh: '美国', en: 'United States' },
  { value: 'United Kingdom', zh: '英国', en: 'United Kingdom' },
  { value: 'Canada', zh: '加拿大', en: 'Canada' },
  { value: 'Australia', zh: '澳大利亚', en: 'Australia' },
  { value: 'New Zealand', zh: '新西兰', en: 'New Zealand' },
  { value: 'Germany', zh: '德国', en: 'Germany' },
  { value: 'France', zh: '法国', en: 'France' },
  { value: 'Italy', zh: '意大利', en: 'Italy' },
  { value: 'Spain', zh: '西班牙', en: 'Spain' },
  { value: 'Netherlands', zh: '荷兰', en: 'Netherlands' },
  { value: 'Switzerland', zh: '瑞士', en: 'Switzerland' },
  { value: 'Sweden', zh: '瑞典', en: 'Sweden' },
  { value: 'Norway', zh: '挪威', en: 'Norway' },
  { value: 'Finland', zh: '芬兰', en: 'Finland' },
  { value: 'Poland', zh: '波兰', en: 'Poland' },
  { value: 'Russia', zh: '俄罗斯', en: 'Russia' },
  { value: 'Turkey', zh: '土耳其', en: 'Turkey' },
  { value: 'South Korea', zh: '韩国', en: 'South Korea' },
  { value: 'Singapore', zh: '新加坡', en: 'Singapore' },
  { value: 'Thailand', zh: '泰国', en: 'Thailand' },
  { value: 'Vietnam', zh: '越南', en: 'Vietnam' },
  { value: 'Malaysia', zh: '马来西亚', en: 'Malaysia' },
  { value: 'Indonesia', zh: '印度尼西亚', en: 'Indonesia' },
  { value: 'Philippines', zh: '菲律宾', en: 'Philippines' },
  { value: 'India', zh: '印度', en: 'India' },
  { value: 'Israel', zh: '以色列', en: 'Israel' },
  { value: 'UAE', zh: '阿联酋', en: 'UAE' },
  { value: 'Saudi Arabia', zh: '沙特阿拉伯', en: 'Saudi Arabia' },
  { value: 'Egypt', zh: '埃及', en: 'Egypt' },
  { value: 'South Africa', zh: '南非', en: 'South Africa' },
  { value: 'Brazil', zh: '巴西', en: 'Brazil' },
  { value: 'Mexico', zh: '墨西哥', en: 'Mexico' },
  { value: 'Argentina', zh: '阿根廷', en: 'Argentina' },
  { value: 'Other', zh: '其他', en: 'Other' },
];

export const TIMEZONES: BilingualOption[] = [
  { value: 'Asia/Shanghai', zh: '亚洲/上海（北京、中国）', en: 'Asia/Shanghai (Beijing, China)' },
  { value: 'Asia/Hong_Kong', zh: '亚洲/香港', en: 'Asia/Hong Kong' },
  { value: 'Asia/Taipei', zh: '亚洲/台北', en: 'Asia/Taipei' },
  { value: 'Asia/Tokyo', zh: '亚洲/东京（日本、韩国）', en: 'Asia/Tokyo (Japan, Korea)' },
  { value: 'Asia/Seoul', zh: '亚洲/首尔', en: 'Asia/Seoul' },
  { value: 'Asia/Singapore', zh: '亚洲/新加坡', en: 'Asia/Singapore' },
  { value: 'Asia/Bangkok', zh: '亚洲/曼谷（泰国、越南）', en: 'Asia/Bangkok (Thailand, Vietnam)' },
  { value: 'Asia/Jakarta', zh: '亚洲/雅加达（印尼）', en: 'Asia/Jakarta (Indonesia)' },
  { value: 'Asia/Kuala_Lumpur', zh: '亚洲/吉隆坡（马来西亚）', en: 'Asia/Kuala Lumpur (Malaysia)' },
  { value: 'Asia/Manila', zh: '亚洲/马尼拉（菲律宾）', en: 'Asia/Manila (Philippines)' },
  { value: 'Asia/Kolkata', zh: '亚洲/加尔各答（印度）', en: 'Asia/Kolkata (India)' },
  { value: 'Asia/Dubai', zh: '亚洲/迪拜（阿联酋）', en: 'Asia/Dubai (UAE)' },
  { value: 'Asia/Riyadh', zh: '亚洲/利雅得（沙特）', en: 'Asia/Riyadh (Saudi Arabia)' },
  { value: 'Asia/Jerusalem', zh: '亚洲/耶路撒冷（以色列）', en: 'Asia/Jerusalem (Israel)' },
  { value: 'Europe/Istanbul', zh: '欧洲/伊斯坦布尔（土耳其）', en: 'Europe/Istanbul (Turkey)' },
  { value: 'America/New_York', zh: '美东（纽约、佛罗里达）', en: 'America/New York (Eastern - NYC, FL)' },
  { value: 'America/Chicago', zh: '美中（芝加哥、德州）', en: 'America/Chicago (Central - TX, IL)' },
  { value: 'America/Denver', zh: '美山区（丹佛、科罗拉多）', en: 'America/Denver (Mountain - CO)' },
  { value: 'America/Los_Angeles', zh: '美西（洛杉矶、西雅图）', en: 'America/Los Angeles (Pacific - CA, WA)' },
  { value: 'America/Anchorage', zh: '美国/阿拉斯加', en: 'America/Anchorage (Alaska)' },
  { value: 'Pacific/Honolulu', zh: '太平洋/夏威夷', en: 'Pacific/Honolulu (Hawaii)' },
  { value: 'America/Toronto', zh: '美洲/多伦多（加拿大东部）', en: 'America/Toronto (Eastern Canada)' },
  { value: 'America/Vancouver', zh: '美洲/温哥华（加拿大西部）', en: 'America/Vancouver (Western Canada)' },
  { value: 'America/Mexico_City', zh: '美洲/墨西哥城', en: 'America/Mexico City' },
  { value: 'America/Sao_Paulo', zh: '美洲/圣保罗（巴西）', en: 'America/São Paulo (Brazil)' },
  { value: 'America/Buenos_Aires', zh: '美洲/布宜诺斯艾利斯（阿根廷）', en: 'America/Buenos Aires (Argentina)' },
  { value: 'Europe/London', zh: '欧洲/伦敦（英国 GMT/BST）', en: 'Europe/London (GMT/BST - UK)' },
  { value: 'Europe/Paris', zh: '欧洲/巴黎（法国）', en: 'Europe/Paris (CET - France)' },
  { value: 'Europe/Berlin', zh: '欧洲/柏林（德国）', en: 'Europe/Berlin (Germany)' },
  { value: 'Europe/Rome', zh: '欧洲/罗马（意大利）', en: 'Europe/Rome (Italy)' },
  { value: 'Europe/Madrid', zh: '欧洲/马德里（西班牙）', en: 'Europe/Madrid (Spain)' },
  { value: 'Europe/Amsterdam', zh: '欧洲/阿姆斯特丹（荷兰）', en: 'Europe/Amsterdam (Netherlands)' },
  { value: 'Europe/Stockholm', zh: '欧洲/斯德哥尔摩（瑞典）', en: 'Europe/Stockholm (Sweden)' },
  { value: 'Europe/Helsinki', zh: '欧洲/赫尔辛基（芬兰）', en: 'Europe/Helsinki (Finland)' },
  { value: 'Europe/Warsaw', zh: '欧洲/华沙（波兰）', en: 'Europe/Warsaw (Poland)' },
  { value: 'Europe/Zurich', zh: '欧洲/苏黎世（瑞士）', en: 'Europe/Zurich (Switzerland)' },
  { value: 'Europe/Oslo', zh: '欧洲/奥斯陆（挪威）', en: 'Europe/Oslo (Norway)' },
  { value: 'Europe/Moscow', zh: '欧洲/莫斯科（俄罗斯）', en: 'Europe/Moscow (MSK - Russia)' },
  { value: 'Africa/Cairo', zh: '非洲/开罗（埃及）', en: 'Africa/Cairo (Egypt)' },
  { value: 'Africa/Johannesburg', zh: '非洲/约翰内斯堡（南非）', en: 'Africa/Johannesburg (South Africa)' },
  { value: 'Australia/Sydney', zh: '澳大利亚/悉尼（AEST）', en: 'Australia/Sydney (AEST)' },
  { value: 'Australia/Perth', zh: '澳大利亚/珀斯（AWST）', en: 'Australia/Perth (AWST)' },
  { value: 'Australia/Melbourne', zh: '澳大利亚/墨尔本', en: 'Australia/Melbourne' },
  { value: 'Pacific/Auckland', zh: '太平洋/奥克兰（新西兰）', en: 'Pacific/Auckland (New Zealand)' },
  { value: 'UTC', zh: 'UTC（协调世界时）', en: 'UTC (Coordinated Universal Time)' },
];

export const LOCAL_CONFIG_TRANSLATIONS = {
  zh: {
    apiTitle: 'AI 核心配置',
    apiDesc: '管理 Gemini API Key 与模型。',
    logTitle: '开发者日志',
    logDesc: '查看应用的实时运行日志。',
    clearLog: '清空日志',
    keyLabel: '主 API KEY (PRIMARY)',
    keyLabel_backup: '备用 API KEY (BACKUP)',
    useEnv: '使用环境变量',
    useEnvDesc: '使用系统环境变量 (process.env.API_KEY)。',
    useCustomEndpoint: '使用自定义接口',
    useCustomEndpointDesc: '覆盖默认的 API 地址 (如使用代理)。',
    customEndpointPlaceholder: 'https://generativelanguage.googleapis.com',
    keyPlaceHolder: '请输入您的 API Key...',
    allocation: '皮层分配',
    slotA: 'SLOT A: 主核心 (MAIN CORE)',
    slotA_desc: '负责主要对话逻辑与人格引擎。',
    slotB: 'SLOT B: 记忆核心 (MEMORY CORE)',
    slotB_desc: '后台负责记忆摘要与日记生成。',
    slotC: 'SLOT C: TTS翻译',
    slotC_desc: '语音翻译模型（可选）：将中文翻译为久美子风格的日文。留空则使用主模型。',
    testConnection: '测试连接',
    validating: '正在测试连接...',
    success: '连接测试通过。',
    error_invalid: '连接测试失败：Key无效、模型名称错误或无法连接服务器。',
    error_env_missing: '连接测试失败：环境变量 API_KEY 为空或无效。',
    validateSearch: '验证搜索/联网能力',
    validatingSearch: '正在验证搜索权限...',
    searchSuccess: '搜索权限已确认。',
    searchFail: '搜索权限未启用或被拒绝。',
    validateModels: '验证模型可用性',
    validatingModels: '正在验证模型...',
    modelValidationWarning: '一个或多个模型当前可能不可用，建议更换。',
    modelAvailable: '模型可用',
    modelUnavailable: '模型不可用或资源耗尽',
    saveAndReload: '保存并强制重启 (立即生效)',
    provider_gemini: 'Google Gemini (默认)',
    provider_openai: 'OpenAI',
    provider_anthropic: 'Anthropic Claude'
  },
  en: {
    apiTitle: 'AI Core Configuration',
    apiDesc: 'Manage Gemini API Key & models.',
    logTitle: 'Developer Log',
    logDesc: 'View real-time application logs.',
    clearLog: 'Clear Log',
    keyLabel: 'PRIMARY API KEY',
    keyLabel_backup: 'BACKUP API KEY',
    useEnv: 'Use Environment Key',
    useEnvDesc: 'Using System Environment Variable (process.env.API_KEY).',
    useCustomEndpoint: 'Use Custom Endpoint',
    useCustomEndpointDesc: 'Override default API URL (e.g., for proxy).',
    customEndpointPlaceholder: 'https://generativelanguage.googleapis.com',
    keyPlaceHolder: 'Enter your API Key...',
    allocation: 'CORTEX ALLOCATION',
    slotA: 'SLOT A: MAIN CORE',
    slotA_desc: 'Primary conversation & personality engine.',
    slotB: 'SLOT B: MEMORY CORE',
    slotB_desc: 'Background summarization & diary generation.',
    slotC: 'SLOT C: TTS TRANSLATION',
    slotC_desc: 'Voice translation model (optional): translates Chinese to Kumiko-style Japanese. Falls back to main model if empty.',
    testConnection: 'TEST CONNECTION',
    validating: 'Testing Connection...',
    success: 'Connection Verified.',
    error_invalid: 'Connection Failed: Invalid Key, Model Name, or Network Error.',
    error_env_missing: 'Connection Failed: Env Variable API_KEY is missing or invalid.',
    validateSearch: 'Verify Grounding (Search)',
    validatingSearch: 'Verifying Search...',
    searchSuccess: 'Search Capability Verified.',
    searchFail: 'Search Permission Denied.',
    validateModels: 'Verify Model Availability',
    validatingModels: 'Verifying models...',
    modelValidationWarning: 'One or more models may be unavailable. Consider switching.',
    modelAvailable: 'Model is available',
    modelUnavailable: 'Model is unavailable or exhausted',
    saveAndReload: 'SAVE & FORCE RESTART',
    provider_gemini: 'Google Gemini (Default)',
    provider_openai: 'OpenAI',
    provider_anthropic: 'Anthropic Claude'
  }
};
